"""Build the machine knowledge file used by all maintenance intelligence."""

import html
import re
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import quote_plus
from urllib.request import Request, urlopen

from app import config
from app.infrastructure.file_storage import FileStorage
from app.infrastructure.logging import get_logger
from app.repositories.base import DocumentRepository, MachineRepository, PartsRepository

log = get_logger("turbofix.machine_data")


def _safe_name(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9._ -]+", "", value or "machine").strip() or "machine"


def machine_data_path(machine: dict, *, internet: bool = False) -> Path:
    suffix = "MachineDataInet" if internet else "MachineData"
    return config.DOCUMENT_STORE_DIR / machine["company_code"] / machine["machine_id"] / f"{_safe_name(machine.get('machine_name'))}{suffix}.md"


async def _document_text(doc: dict, storage: FileStorage) -> str:
    try:
        content = await storage.read(doc["storage_path"])
        extension = Path(doc.get("file_name", "")).suffix.lower()
        if extension in {".txt", ".md", ".csv"}:
            return content.decode("utf-8", errors="ignore")[:12000]
        return f"Binary document uploaded: {doc.get('file_name', 'unnamed file')} ({len(content)} bytes)."
    except Exception as exc:
        log.warning("machine_data.document_read_failed", document=doc.get("document_id"), error=str(exc))
        return f"Document metadata only: {doc.get('file_name', 'unnamed file')}."


def _missing_sections(documents: list[dict], parts: list[dict]) -> list[str]:
    categories = {str(doc.get("category", "")).lower() for doc in documents}
    missing = []
    if not categories.intersection({"manual", "other"}):
        missing.append("operating manual")
    if not categories.intersection({"circuit_diagram", "hydraulic_diagram"}):
        missing.append("wiring or hydraulic diagram")
    if not categories.intersection({"spare_parts_catalog"}) and not parts:
        missing.append("bill of material or spare part list")
    return missing


async def build_machine_data(
    *, machine: dict, documents: DocumentRepository, parts: PartsRepository,
    storage: FileStorage, internet: bool = False,
) -> dict:
    docs = documents.list(machine["company_code"], machine["machine_id"])
    spare_parts = parts.list_items("spare_parts", machine["company_code"], machine["machine_id"])
    consumables = parts.list_items("consumables", machine["company_code"], machine["machine_id"])
    sections = []
    for doc in docs:
        sections.append(f"### {doc.get('title') or doc.get('file_name')}\n\n{await _document_text(doc, storage)}")

    missing = _missing_sections(docs, spare_parts)
    source_note = "Uploaded factory documents and inventory records"
    if internet:
        source_note = "Uploaded factory documents, inventory records, and user-approved internet references"
        sections.append(await _internet_reference(machine))

    content = f"""# {machine.get('machine_name', machine.get('machine_id'))} — Machine Data

> Generated by TurboFix on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}.
> Source: {source_note}.
> This file is the canonical context for TurboFix AI recommendations for this machine.

## Machine Identity
- Machine ID: {machine.get('machine_id', '')}
- Name: {machine.get('machine_name', '')}
- Location: {machine.get('location', '')}
- Assigned technician: {machine.get('assigned_technician_phone', '')}

## Spare Parts and Bill of Material
{_list_items(spare_parts, ('part_name', 'part_number', 'quantity_on_hand', 'unit', 'reorder_level', 'supplier'))}

## Consumables
{_list_items(consumables, ('name', 'quantity_on_hand', 'unit', 'reorder_level', 'notes'))}

## Uploaded Technical Knowledge
{chr(10).join(sections) if sections else 'No technical documents uploaded yet.'}

## Data Gaps
{', '.join(missing) if missing else 'No known data gaps.'}
"""
    path = machine_data_path(machine, internet=internet)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    log.info("machine_data.generated", machine_id=machine["machine_id"], path=str(path), internet=internet)
    return {"file_name": path.name, "path": str(path), "missing_sections": missing, "internet": internet}


def _list_items(items: list[dict], fields: tuple[str, ...]) -> str:
    if not items:
        return "No records available."
    return "\n".join("- " + "; ".join(f"{field}: {item.get(field, '')}" for field in fields if item.get(field, '') not in (None, "")) for item in items)


async def _internet_reference(machine: dict) -> str:
    query = quote_plus(f"{machine.get('machine_name', '')} maintenance manual specifications")
    url = f"https://html.duckduckgo.com/html/?q={query}"
    try:
        request = Request(url, headers={"User-Agent": "TurboFix/1.0 maintenance research"})
        with urlopen(request, timeout=10) as response:
            raw = response.read().decode("utf-8", errors="ignore")
        text = html.unescape(re.sub(r"<[^>]+>", " ", raw))
        text = re.sub(r"\s+", " ", text).strip()
        return f"## User-Approved Internet Reference\n\nSearch: `{machine.get('machine_name', '')} maintenance manual specifications`\n\nSource: {url}\n\n{ text[:5000] }"
    except Exception as exc:
        log.warning("machine_data.internet_lookup_failed", machine_id=machine.get("machine_id"), error=str(exc))
        return "## User-Approved Internet Reference\n\nInternet lookup was approved but unavailable. Verify technical specifications against the OEM manual before acting."


def read_machine_data(machine: dict, *, internet: bool = False) -> str:
    path = machine_data_path(machine, internet=internet)
    if not path.exists() and internet:
        path = machine_data_path(machine)
    return path.read_text(encoding="utf-8") if path.exists() else ""
