import React, { useEffect, useMemo, useState } from 'react';
import AppShell from '../components/AppShell';
import { apiFetch } from '@/lib/api';

export default function ShutdownPlanner() {
  const [machines, setMachines] = useState([]); const [tickets, setTickets] = useState([]); const [date, setDate] = useState(''); const [hours, setHours] = useState('8');
  useEffect(() => { Promise.all([apiFetch('/vault/machines'), apiFetch('/vault/tickets')]).then(async ([m, t]) => { setMachines(m.ok ? await m.json() : []); setTickets(t.ok ? await t.json() : []); }).catch(() => {}); }, []);
  const plan = useMemo(() => machines.map((machine) => { const issues = tickets.filter((ticket) => ticket.machine_id === machine.machine_id && ticket.status === 'Open'); return { ...machine, issues, priority: issues.some((ticket) => ticket.urgency === 'High') ? 'Critical' : issues.length ? 'Recommended' : 'Preventive' }; }).sort((a, b) => ({ Critical: 0, Recommended: 1, Preventive: 2 }[a.priority] - ({ Critical: 0, Recommended: 1, Preventive: 2 }[b.priority]))), [machines, tickets]);
  return <AppShell active="shutdown"><div className="planner-page"><div className="decision-heading"><div><span className="eyebrow eyebrow-light">AI shutdown planner</span><h1>Build the right shutdown plan</h1><p>Turn one planned stop into a prioritized worklist for your maintenance team.</p></div><a className="btn btn-ghost btn-sm" href="machines.html">Manage machines</a></div>
    <section className="planner-controls"><label>Shutdown date<input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></label><label>Available hours<input type="number" min="1" value={hours} onChange={(e) => setHours(e.target.value)} /></label><div className="planner-summary"><strong>{plan.length}</strong><span>machines in scope</span></div><div className="planner-summary"><strong>{plan.filter((m) => m.priority !== 'Preventive').length}</strong><span>priority actions</span></div></section>
    <section className="decision-panel planner-panel"><div className="decision-panel-heading"><div><div className="decision-card-kicker">Recommended sequence</div><h2>{date ? `Plan for ${new Date(`${date}T00:00:00`).toLocaleDateString()}` : 'Choose a shutdown date'}</h2></div><span className="trend-caption">{hours} hours available</span></div>{plan.length ? plan.map((machine, index) => <div className="planner-row" key={machine.machine_id}><span className="planner-order">{index + 1}</span><div><strong>{machine.machine_name}</strong><span>{machine.location || machine.machine_id} · {machine.issues.length ? `${machine.issues.length} open issue${machine.issues.length > 1 ? 's' : ''}` : 'PM candidate'}</span></div><b className={`planner-priority ${machine.priority.toLowerCase()}`}>{machine.priority}</b><span className="planner-estimate">~{machine.issues.length ? 2 : 1} hr</span></div>) : <p className="decision-empty">Register machines to generate an optimized shutdown sequence.</p>}</section>
    <div className="planner-note"><strong>Next step:</strong> review machine manuals and spare availability in the <a href="machines.html">machine workspace</a>, then generate work orders for the approved sequence.</div>
  </div></AppShell>;
}
