import React, { useState } from 'react';
import { X, Copy, Send, Check, FileText, Calendar } from 'lucide-react';

export function ShiftHandoverModal({ open, onClose, tickets = [], machines = [] }) {
  const [copied, setCopied] = useState(false);

  if (!open) return null;

  const nowStr = new Date().toLocaleString('en-IN', {
    dateStyle: 'medium',
    timeStyle: 'short',
  });

  const openTickets = tickets.filter((t) => String(t.status || 'Open').toLowerCase() === 'open');
  const criticalTickets = openTickets.filter((t) => String(t.urgency || '').toLowerCase() === 'critical');
  const waitingSpareTickets = openTickets.filter((t) => t.lifecycle_stage === 'waiting_spare');
  const inProgressTickets = openTickets.filter((t) => t.lifecycle_stage === 'work_started');

  const summaryText = `📋 *TURBOFIX SHIFT HANDOVER SUMMARY*
📅 *Generated:* ${nowStr}
----------------------------------
📊 *PLANT SUMMARY:*
• Open Work Orders: ${openTickets.length}
• Critical Breakdown Alerts: ${criticalTickets.length}
• In-Progress Repairs: ${inProgressTickets.length}
• Waiting for Spares: ${waitingSpareTickets.length}

🚨 *CRITICAL BREAKDOWNS:*
${
  criticalTickets.length === 0
    ? '• None — Plant critical machines running.'
    : criticalTickets
        .map((t) => `• ${t.machine_name || 'Machine'}: ${t.issue_text || t.description || 'Issue'} (${t.technician_name || 'Unassigned'})`)
        .join('\n')
}

⏳ *WAITING SPARES / ACTION ITEMS:*
${
  waitingSpareTickets.length === 0
    ? '• No pending part requests.'
    : waitingSpareTickets
        .map((t) => `• ${t.machine_name}: ${t.parts_used || 'Parts pending allocation'}`)
        .join('\n')
}

----------------------------------
_Automated handover digest generated by TurboFix Industrial OS_`;

  const handleCopy = () => {
    navigator.clipboard.writeText(summaryText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div
      style={{
        position: 'fixed',
        inset: 0,
        zIndex: 99999,
        background: 'rgba(0, 0, 0, 0.8)',
        backdropFilter: 'blur(6px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 16,
      }}
      onClick={onClose}
    >
      <div
        style={{
          background: 'var(--surface-card, #1E293B)',
          borderRadius: 16,
          border: '1px solid rgba(255, 255, 255, 0.12)',
          maxWidth: 520,
          width: '100%',
          padding: 20,
          boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.5)',
          color: '#F8FAFC',
        }}
        onClick={(e) => e.stopPropagation()}
      >
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <div style={{ padding: 8, background: 'rgba(56,189,248,0.15)', borderRadius: 10, color: '#38BDF8' }}>
              <FileText size={20} />
            </div>
            <div>
              <h3 style={{ margin: 0, fontSize: '1.05rem', fontWeight: 600 }}>Shift Handover Digest</h3>
              <p style={{ margin: 0, fontSize: '0.78rem', color: '#94A3B8' }}>Instant summary for oncoming shift supervisor</p>
            </div>
          </div>
          <button onClick={onClose} style={{ background: 'none', border: 'none', color: '#94A3B8', cursor: 'pointer' }}>
            <X size={20} />
          </button>
        </div>

        <textarea
          readOnly
          value={summaryText}
          rows={12}
          style={{
            width: '100%',
            background: 'rgba(15, 23, 42, 0.8)',
            border: '1px solid rgba(255,255,255,0.1)',
            borderRadius: 10,
            padding: 12,
            color: '#E2E8F0',
            fontFamily: 'monospace',
            fontSize: '0.8rem',
            resize: 'none',
            boxSizing: 'border-box',
            marginBottom: 16,
          }}
        />

        <div style={{ display: 'flex', justifyContent: 'space-between', gap: 8 }}>
          <button
            onClick={handleCopy}
            style={{
              padding: '8px 16px',
              borderRadius: 8,
              background: copied ? '#10B981' : 'rgba(255,255,255,0.08)',
              border: '1px solid rgba(255,255,255,0.15)',
              color: '#FFFFFF',
              fontWeight: 600,
              display: 'flex',
              alignItems: 'center',
              gap: 6,
              cursor: 'pointer',
            }}
          >
            {copied ? <Check size={16} /> : <Copy size={16} />}
            {copied ? 'Copied!' : 'Copy Summary'}
          </button>

          <div style={{ display: 'flex', gap: 8 }}>
            <a
              href={`https://wa.me/?text=${encodeURIComponent(summaryText)}`}
              target="_blank"
              rel="noopener noreferrer"
              style={{
                padding: '8px 16px',
                borderRadius: 8,
                background: 'rgba(34,197,94,0.18)',
                border: '1px solid rgba(34,197,94,0.4)',
                color: '#4ADE80',
                fontWeight: 600,
                textDecoration: 'none',
                display: 'inline-flex',
                alignItems: 'center',
                gap: 6,
              }}
            >
              <Send size={16} /> Share via WhatsApp
            </a>
            <button
              onClick={onClose}
              style={{
                padding: '8px 16px',
                borderRadius: 8,
                background: '#0EA5E9',
                border: 'none',
                color: '#FFFFFF',
                fontWeight: 600,
                cursor: 'pointer',
              }}
            >
              Done
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
