// Demo tickets for development and demonstrations
// Remove or disable in production

export const DEMO_TICKETS = [
  {
    id: 'T005',
    ticket_id: 'T005',
    wo_number: 'WO-00005',
    machine_id: 'DEMO-M001',
    machine_name: 'CNC Lathe 1',
    company_code: 'ACME3',
    description: 'Spindle vibration returned after restart',
    ai_summary: 'Repeat spindle bearing issue; inspect bearing seating and lubrication circuit',
    urgency: 'High',
    status: 'reported',
    lifecycle_stage: 'reported',
    reported_at: new Date(2026, 6, 10, 11, 15).toISOString(),
    reporter_phone: '+919900011115',
    language: 'en',
  },
  {
    id: 'T006',
    ticket_id: 'T006',
    wo_number: 'WO-00006',
    machine_id: 'DEMO-M002',
    machine_name: 'Hydraulic Press #2',
    company_code: 'ACME3',
    description: 'Pressure drops during the final stroke',
    ai_summary: 'Hydraulic pressure loss; check seal kit and pressure relief valve',
    urgency: 'High',
    status: 'reported',
    lifecycle_stage: 'reported',
    reported_at: new Date(2026, 6, 12, 14, 20).toISOString(),
    reporter_phone: '+919900011116',
    language: 'en',
  },
  {
    id: 'T007',
    ticket_id: 'T007',
    wo_number: 'WO-00007',
    machine_id: 'DEMO-M003',
    machine_name: 'Surface Grinder',
    company_code: 'ACME3',
    description: 'Coolant pump failed - no fluid circulation',
    ai_summary: 'Pump motor seized; check impeller blockage and motor winding resistance',
    urgency: 'High',
    status: 'reported',
    lifecycle_stage: 'reported',
    reported_at: new Date(2026, 6, 13, 9, 45).toISOString(),
    reporter_phone: '+919900011117',
    language: 'en',
  },
  {
    id: 'T008',
    ticket_id: 'T008',
    wo_number: 'WO-00008',
    machine_id: 'DEMO-M004',
    machine_name: 'Air Compressor 75kW',
    company_code: 'ACME3',
    description: 'Air discharge temperature exceeds 95°C',
    ai_summary: 'Intercooler fouled or thermal valve stuck; inspect cooling passages and replace if necessary',
    urgency: 'High',
    status: 'reported',
    lifecycle_stage: 'reported',
    reported_at: new Date(2026, 6, 14, 16, 30).toISOString(),
    reporter_phone: '+919900011118',
    language: 'en',
  },
  {
    id: 'T009',
    ticket_id: 'T009',
    wo_number: 'WO-00009',
    machine_id: 'DEMO-M005',
    machine_name: 'Packing Conveyor',
    company_code: 'ACME3',
    description: 'Servo motor position drift - wrapping quality degraded',
    ai_summary: 'Encoder misalignment or servo calibration drift; recalibrate position feedback and motor parameters',
    urgency: 'High',
    status: 'reported',
    lifecycle_stage: 'reported',
    reported_at: new Date(2026, 6, 15, 13, 10).toISOString(),
    reporter_phone: '+919900011119',
    language: 'en',
  },
];
