// Demo tickets for development and demonstrations
// Remove or disable in production

export const DEMO_TICKETS = [
  {
    id: 'T005',
    ticket_id: 'T005',
    wo_number: 'WO-00005',
    machine_id: 'DEMO-M001',
    machine_name: 'CNC Lathe 1',
    company_code: 'DEMO-PLANT',
    description: 'Spindle motor vibration above threshold – bearing wear suspected',
    ai_summary: 'Repeat spindle bearing issue; inspect bearing seating and lubrication circuit',
    urgency: 'High',
    status: 'reported',
    lifecycle_stage: 'reported',
    reported_at: new Date(2026, 6, 10, 11, 15).toISOString(),
    created_at: new Date(2026, 6, 10, 11, 15).toISOString(),
    reporter_phone: '+919900011115',
    language: 'en',
    loto_confirmed: false,
    downtime_hours: 4.5,
    permit_number: 'PTW-2026-001',
  },
  {
    id: 'T006',
    ticket_id: 'T006',
    wo_number: 'WO-00006',
    machine_id: 'DEMO-M002',
    machine_name: 'Hydraulic Press #2',
    company_code: 'DEMO-PLANT',
    description: 'Pressure drops during the final stroke, unable to maintain holding force',
    ai_summary: 'Hydraulic pressure loss; check seal kit and pressure relief valve',
    urgency: 'Medium',
    status: 'reported',
    lifecycle_stage: 'reported',
    reported_at: new Date(2026, 6, 12, 14, 20).toISOString(),
    created_at: new Date(2026, 6, 12, 14, 20).toISOString(),
    reporter_phone: '+919900011116',
    language: 'en',
    loto_confirmed: false,
    downtime_hours: 2,
    permit_number: null,
  },
  {
    id: 'T007',
    ticket_id: 'T007',
    wo_number: 'WO-00007',
    machine_id: 'DEMO-M003',
    machine_name: 'Surface Grinder',
    company_code: 'DEMO-PLANT',
    description: 'Coolant pump failed - no fluid circulation, motor making humming noise',
    ai_summary: 'Pump motor seized; check impeller blockage and motor winding resistance',
    urgency: 'Medium',
    status: 'reported',
    lifecycle_stage: 'reported',
    reported_at: new Date(2026, 6, 13, 9, 45).toISOString(),
    created_at: new Date(2026, 6, 13, 9, 45).toISOString(),
    reporter_phone: '+919900011117',
    language: 'en',
    loto_confirmed: false,
    downtime_hours: 3.5,
    permit_number: 'PTW-2026-002',
  },
  {
    id: 'T008',
    ticket_id: 'T008',
    wo_number: 'WO-00008',
    machine_id: 'DEMO-M004',
    machine_name: 'Air Compressor 75kW',
    company_code: 'DEMO-PLANT',
    description: 'Air discharge temperature exceeds 95°C, causing auto-shutdown',
    ai_summary: 'Intercooler fouled or thermal valve stuck; inspect cooling passages and replace if necessary',
    urgency: 'Critical',
    status: 'reported',
    lifecycle_stage: 'reported',
    reported_at: new Date(2026, 6, 14, 16, 30).toISOString(),
    created_at: new Date(2026, 6, 14, 16, 30).toISOString(),
    reporter_phone: '+919900011118',
    language: 'en',
    loto_confirmed: false,
    downtime_hours: 8,
    permit_number: 'PTW-2026-003',
  },
  {
    id: 'T009',
    ticket_id: 'T009',
    wo_number: 'WO-00009',
    machine_id: 'DEMO-M005',
    machine_name: 'Packing Conveyor',
    company_code: 'DEMO-PLANT',
    description: 'Servo motor position drift - wrapping quality degraded and material jam',
    ai_summary: 'Encoder misalignment or servo calibration drift; recalibrate position feedback and motor parameters',
    urgency: 'Low',
    status: 'reported',
    lifecycle_stage: 'reported',
    reported_at: new Date(2026, 6, 15, 13, 10).toISOString(),
    created_at: new Date(2026, 6, 15, 13, 10).toISOString(),
    reporter_phone: '+919900011119',
    language: 'en',
    loto_confirmed: false,
    downtime_hours: 0.5,
    permit_number: null,
  },
  {
    id: 'T010',
    ticket_id: 'T010',
    wo_number: 'WO-00010',
    machine_id: 'DEMO-M001',
    machine_name: 'CNC Lathe 1',
    company_code: 'DEMO-PLANT',
    description: 'Turret index failure during tool change cycle, error code AL-42',
    ai_summary: 'Turret clamp sensor fault; verify sensor alignment and clean debris',
    urgency: 'High',
    status: 'reported',
    lifecycle_stage: 'reported',
    reported_at: new Date(2026, 6, 16, 8, 0).toISOString(),
    created_at: new Date(2026, 6, 16, 8, 0).toISOString(),
    reporter_phone: '+919900011120',
    language: 'en',
    loto_confirmed: false,
    downtime_hours: 5,
    permit_number: 'PTW-2026-004',
  },
  {
    id: 'T011',
    ticket_id: 'T011',
    wo_number: 'WO-00011',
    machine_id: 'DEMO-M002',
    machine_name: 'Hydraulic Press #2',
    company_code: 'DEMO-PLANT',
    description: 'Safety light curtain intermittent fault, stopping operation randomly',
    ai_summary: 'Light curtain relay chatter; inspect wiring connections and receiver alignment',
    urgency: 'Medium',
    status: 'reported',
    lifecycle_stage: 'reported',
    reported_at: new Date(2026, 6, 17, 10, 30).toISOString(),
    created_at: new Date(2026, 6, 17, 10, 30).toISOString(),
    reporter_phone: '+919900011121',
    language: 'en',
    loto_confirmed: false,
    downtime_hours: 1.5,
    permit_number: null,
  },
  {
    id: 'T012',
    ticket_id: 'T012',
    wo_number: 'WO-00012',
    machine_id: 'DEMO-M003',
    machine_name: 'Surface Grinder',
    company_code: 'DEMO-PLANT',
    description: 'Spindle RPM fluctuating under load, finish quality rejected',
    ai_summary: 'VFD parameter drift or failing drive capacitor; monitor DC bus voltage',
    urgency: 'Medium',
    status: 'reported',
    lifecycle_stage: 'reported',
    reported_at: new Date(2026, 6, 18, 11, 45).toISOString(),
    created_at: new Date(2026, 6, 18, 11, 45).toISOString(),
    reporter_phone: '+919900011122',
    language: 'en',
    loto_confirmed: false,
    downtime_hours: 6,
    permit_number: 'PTW-2026-005',
  },
  {
    id: 'T013',
    ticket_id: 'T013',
    wo_number: 'WO-00013',
    machine_id: 'DEMO-M004',
    machine_name: 'Air Compressor 75kW',
    company_code: 'DEMO-PLANT',
    description: 'Oil separator element high delta P alarm',
    ai_summary: 'Separator filter clogged; schedule element replacement during next downtime',
    urgency: 'Low',
    status: 'reported',
    lifecycle_stage: 'reported',
    reported_at: new Date(2026, 6, 19, 9, 10).toISOString(),
    created_at: new Date(2026, 6, 19, 9, 10).toISOString(),
    reporter_phone: '+919900011123',
    language: 'en',
    loto_confirmed: false,
    downtime_hours: 1,
    permit_number: null,
  },
  {
    id: 'T014',
    ticket_id: 'T014',
    wo_number: 'WO-00014',
    machine_id: 'DEMO-M005',
    machine_name: 'Packing Conveyor',
    company_code: 'DEMO-PLANT',
    description: 'Pneumatic cylinder for reject gate leaking air',
    ai_summary: 'Cylinder seal worn; replace seal kit or entire cylinder assembly',
    urgency: 'Low',
    status: 'reported',
    lifecycle_stage: 'reported',
    reported_at: new Date(2026, 6, 20, 15, 0).toISOString(),
    created_at: new Date(2026, 6, 20, 15, 0).toISOString(),
    reporter_phone: '+919900011124',
    language: 'en',
    loto_confirmed: false,
    downtime_hours: 2.5,
    permit_number: null,
  },
];
