export function exportToCSV(data, filename = 'export.csv') {
  if (!data || data.length === 0) {
    console.warn('No data to export');
    return;
  }

  const headers = Object.keys(data[0]);
  const csvContent = [
    headers.join(','),
    ...data.map(row =>
      headers.map(header => {
        const value = row[header];
        if (value === null || value === undefined) return '';
        if (typeof value === 'string' && value.includes(',')) {
          return `"${value.replace(/"/g, '""')}"`;
        }
        return value;
      }).join(',')
    )
  ].join('\n');

  downloadFile(csvContent, filename, 'text/csv');
}

export function exportToJSON(data, filename = 'export.json') {
  const jsonContent = JSON.stringify(data, null, 2);
  downloadFile(jsonContent, filename, 'application/json');
}

export function exportToTSV(data, filename = 'export.tsv') {
  if (!data || data.length === 0) {
    console.warn('No data to export');
    return;
  }

  const headers = Object.keys(data[0]);
  const tsvContent = [
    headers.join('\t'),
    ...data.map(row =>
      headers.map(header => row[header] || '').join('\t')
    )
  ].join('\n');

  downloadFile(tsvContent, filename, 'text/tab-separated-values');
}

export function exportToExcel(data, filename = 'export.xls') {
  if (!data || data.length === 0) {
    console.warn('No data to export');
    return;
  }

  const headers = Object.keys(data[0]);
  const htmlContent = `
    <html>
      <head>
        <meta charset="UTF-8">
        <style>
          table { border-collapse: collapse; width: 100%; }
          th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
          th { background-color: #4CAF50; color: white; font-weight: bold; }
          tr:nth-child(even) { background-color: #f2f2f2; }
        </style>
      </head>
      <body>
        <table>
          <thead>
            <tr>${headers.map(h => `<th>${h}</th>`).join('')}</tr>
          </thead>
          <tbody>
            ${data.map(row => `
              <tr>${headers.map(h => `<td>${row[h] || ''}</td>`).join('')}</tr>
            `).join('')}
          </tbody>
        </table>
      </body>
    </html>
  `;

  downloadFile(htmlContent, filename, 'application/vnd.ms-excel');
}

export function exportToPDF(content, filename = 'export.pdf') {
  const htmlContent = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8">
        <title>${filename}</title>
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 900px;
            margin: 40px auto;
            padding: 20px;
          }
          h1 { color: #25D366; border-bottom: 3px solid #25D366; padding-bottom: 10px; }
          h2 { color: #128C7E; margin-top: 30px; }
          table { border-collapse: collapse; width: 100%; margin: 20px 0; }
          th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
          th { background-color: #25D366; color: white; font-weight: bold; }
          tr:nth-child(even) { background-color: #f9f9f9; }
          .footer { margin-top: 40px; border-top: 1px solid #ddd; padding-top: 10px; font-size: 0.9em; color: #666; }
        </style>
      </head>
      <body>
        ${content}
        <div class="footer">
          <p>Generated by TurboFix on ${new Date().toLocaleString()}</p>
        </div>
      </body>
    </html>
  `;

  const printWindow = window.open('', '', 'width=800,height=600');
  printWindow.document.write(htmlContent);
  printWindow.document.close();
  printWindow.print();
}

function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function generateReport(data, options = {}) {
  const {
    title = 'Report',
    format = 'pdf',
    filename = `${title.toLowerCase()}_${Date.now()}`,
    includeTimestamp = true,
    includeSummary = true
  } = options;

  let content = `<h1>${title}</h1>`;

  if (includeTimestamp) {
    content += `<p><small>Generated on ${new Date().toLocaleString()}</small></p>`;
  }

  if (includeSummary && data.summary) {
    content += `<h2>Summary</h2><pre>${JSON.stringify(data.summary, null, 2)}</pre>`;
  }

  if (data.details) {
    content += `<h2>Details</h2>${data.details}`;
  }

  if (data.tables && Array.isArray(data.tables)) {
    data.tables.forEach(table => {
      content += `<h3>${table.title}</h3>`;
      content += `<table><thead><tr>${table.headers.map(h => `<th>${h}</th>`).join('')}</tr></thead>`;
      content += `<tbody>${table.rows.map(row => `<tr>${row.map(cell => `<td>${cell}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
    });
  }

  switch (format.toLowerCase()) {
    case 'pdf':
      exportToPDF(content, `${filename}.pdf`);
      break;
    case 'csv':
      if (data.rows) {
        exportToCSV(data.rows, `${filename}.csv`);
      }
      break;
    case 'json':
      exportToJSON(data, `${filename}.json`);
      break;
    case 'excel':
      if (data.rows) {
        exportToExcel(data.rows, `${filename}.xls`);
      }
      break;
    default:
      console.warn(`Unsupported format: ${format}`);
  }
}
