import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Background Sync for POST requests (like submitting tickets offline)
const bgSyncPlugin = new BackgroundSyncPlugin('ticketQueue', {
  maxRetentionTime: 24 * 60 // Retry for max of 24 Hours (specified in minutes)
});

// Cache GET requests to the Supabase REST API (for offline vault/inventory viewing)
registerRoute(
  ({ url }) => url.href.includes('/rest/v1/'),
  new NetworkFirst({
    cacheName: 'supabase-api-cache',
    plugins: []
  })
);

// Queue POST requests to edge functions (like ticket_gateway) for offline sync
registerRoute(
  ({ url, request }) => request.method === 'POST' && url.href.includes('/functions/v1/'),
  new NetworkFirst({
    cacheName: 'supabase-mutations-cache',
    plugins: [bgSyncPlugin]
  }),
  'POST'
);

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
