CREATE TABLE IF NOT EXISTS public.whatsapp_conversations (
  phone_e164 text PRIMARY KEY,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  company_id uuid REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  role text NOT NULL,
  graph jsonb NOT NULL DEFAULT '{"nodes":[],"edges":[]}'::jsonb,
  summary text NOT NULL DEFAULT '',
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.whatsapp_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone_e164 text NOT NULL REFERENCES public.whatsapp_conversations(phone_e164) ON DELETE CASCADE,
  direction text NOT NULL CHECK (direction IN ('in','out')),
  content text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS whatsapp_messages_phone_created_idx
  ON public.whatsapp_messages(phone_e164, created_at DESC);

ALTER TABLE public.whatsapp_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_messages ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.whatsapp_conversations FROM anon, authenticated;
REVOKE ALL ON public.whatsapp_messages FROM anon, authenticated;
GRANT ALL ON public.whatsapp_conversations, public.whatsapp_messages TO service_role;
